### ISSUE TITLE
django.db.utils.ProgrammingError: function update_paths() does not exist

### ISSUE THREAD

**Issue by Shubhechchha** [BertrandBordage/django-tree#3]
Hi there,

My current setup is:
Python 3.6
Django 2.0
Postgresql 10.1

I have created a Model and added the respective migraiton for trigger.

`
from django.db import migrations
from tree.operations import CreateTreeTrigger

class Migration(migrations.Migration):
    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        CreateTreeTrigger('relationship.Relationship'),
    ]
`
Upon running the migrate command, I get the following error:
```
File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
app_server_1  |     return self.cursor.execute(sql, params)
app_server_1  | psycopg2.ProgrammingError: function update_paths() does not exist
app_server_1  | 
app_server_1  | 
app_server_1  | The above exception was the direct cause of the following exception:
app_server_1  | 
app_server_1  | Traceback (most recent call last):
app_server_1  |   File "manage.py", line 22, in <module>
app_server_1  |     execute_from_command_line(sys.argv)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
app_server_1  |     utility.execute()
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
app_server_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
app_server_1  |     self.execute(*args, **cmd_options)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
app_server_1  |     output = self.handle(*args, **options)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
app_server_1  |     fake_initial=fake_initial,
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
app_server_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
app_server_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
app_server_1  |     state = migration.apply(state, schema_editor)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
app_server_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/tree/operations.py", line 104, in database_forwards
app_server_1  |     **self.get_pre_params(self.get_model(app_label, to_state))))
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
app_server_1  |     cursor.execute(sql, params)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
app_server_1  |     return super().execute(sql, params)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
app_server_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
app_server_1  |     return executor(sql, params, many, context)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
app_server_1  |     return self.cursor.execute(sql, params)
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
app_server_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_server_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
app_server_1  |     return self.cursor.execute(sql, params)
app_server_1  | django.db.utils.ProgrammingError: function update_paths() does not exist
```
Could you provide some suggestions?

**Comment by MikeSandford** [comment]
I had a similar problem trying to get started myself.  If you look at the documentation, it depends on the initial `tree` migration.  I believe that migration is the one that creates the postgresql function `update_paths()`

```
from django.db import migrations
from tree.operations import CreateTreeTrigger

class Migration(migrations.Migration):
    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        CreateTreeTrigger('your_app.YourModel'),
    ]
```
Your migration file depends only on `('relationship', '0001_initial'),` but it also needs to depend on `('tree', '0001_initial'),` (or perhaps only on the tree initial) migration in order to work.

**Comment by BertrandBordage** [comment]
Thank you @MikeSandford! This should indeed be the correct solution.
Marking the issue as solved, please reopen if it happens again for a different reason.
